const fs = require("fs");

export default async (req, res) => {
  try {
    const phrases = [
      "Are",
      "Are you",
      "Are you sure",
      "Are you sure about",
      "Are you sure of",
      "Are you sure of what",
      "Are you sure of what you",
      "Are you sure that",
      "Are you sure that he",
      "Are you sure that he is",
      "Are you sure that he is not",
      "Are you used",
      "Are you used to",
      "Are you used to using",
      "Are you used to life",
      "Are you used to staying",
      "Are you used to staying up",
      "As",
      "As far",
      "As far as",
      "As far as I",
      "As far as I can",
      "he",
      "he didn’t",
      "he didn’t come",
      "he didn’t come home",
      "he didn’t come home until",
      "there",
      "there were",
      "there were few",
      "there were few people",
      "there were few people in",
      "there were few people in the",
      "there were few people in the village",
      "they",
      "they quarreled",
      "they quarreled very",
      "they quarreled very often",
      "they quarreled very often at",
      "they quarreled very often at that",
      "he’s",
      "he’s a",
      "he’s a big",
      "As far as I’m",
      "I",
      "I don’t",
      "I don’t mind",
      "I don’t mind that",
      "I don’t mind that you",
      "I don’t mind that you wear",
      "I don’t mind that you wear this",
      "The",
      "The coat",
      "The coat is",
      "The coat is fine",
      "The coat is fine as",
      "The coat is fine as far",
      "The coat is fine as far as",
      "The coat is fine as far as color",
      "The coat is fine as far as color is",
      "but",
      "but it",
      "but it is",
      "but it is not",
      "but it is not very",
      "but it is not very good",
      "So",
      "So far",
      "So far as",
      "So far as he’s",
      "nothing",
      "nothing is",
      "nothing is as",
      "nothing is as important",
      "nothing is as important as",
      "nothing is as important as his",
      "We",
      "We are",
      "We are your",
      "but ",
      "but  this",
      "but  this doesn’t",
      "but  this doesn’t mean",
      "but  this doesn’t mean that ",
      "but  this doesn’t mean that  we",
      "but  this doesn’t mean that  we must ",
      "but  this doesn’t mean that  we must  obey",
      "You",
      "You are",
      "You are much",
      "You are much older",
      "You are much older than",
      "You are much older than I",
      "but it doesn’t",
      "but it doesn’t mean",
      "but it doesn’t mean that",
      "but it doesn’t mean that you",
      "but it doesn’t mean that you are",
      "but it doesn’t mean that you are right",
      "I ",
      "I  support ",
      "I  support  this",
      "but  it ",
      "but  it  doesn’t",
      "but  it  doesn’t mean",
      "but  it  doesn’t mean that ",
      "but  it  doesn’t mean that  I ",
      "but  it  doesn’t mean that  I  support ",
      "but  it  doesn’t mean that  I  support  you ",
      "I like",
      "but this",
      "but this doesn’t",
      "but this doesn’t mean",
      "but this doesn’t mean that",
      "but this doesn’t mean that I’ll",
      "but this doesn’t mean that I’ll marry",
      "Be",
      "Be careful",
      "Be careful with",
      "Be careful with the",
      "Be careful with the wet",
      "Be careful that",
      "Be careful that you",
      "Be careful that you don’t ",
      "Be careful that you don’t  catch",
      "Be careful that you don’t  catch a",
      "Be careful that you don’t  catch a cold",
      "Be careful that you don’t  catch a cold Put",
      "Be careful that you don’t  catch a cold Put on",
      "Be careful that you don’t  catch a cold Put on more",
      "Be careful that you don’t  catch a cold Put on more clothes",
      "Be careful that you don’t  catch a cold Put on more clothes before",
      "Be careful that you don’t  catch a cold Put on more clothes before you",
      "Be careful not",
      "Be careful not to",
      "Be careful not to spill",
      "Be careful not to spill the",
      "Compared",
      "Compared to",
      "Compared to other",
      "she",
      "she is",
      "she is quite",
      "she is quite hard",
      "Compared to city",
      "country",
      "country life",
      "country life is",
      "country life is quiet",
      "country life is quiet and",
      "air-conditioners",
      "air-conditioners are",
      "air-conditioners are more",
      "By",
      "By the",
      "is",
      "is there",
      "is there a",
      "is there a bathroom",
      "is there a bathroom in",
      "is there a bathroom in the",
      "do",
      "do you",
      "do you have",
      "do you have any",
      "do you have any change",
      "do you have any change on",
      "he is",
      "he is a",
      "he is a difficult",
      "Don’t",
      "Don’t ever",
      "Don’t ever lose",
      "Don’t ever lose these",
      "Don’t ever lose these papers",
      "Don’t ever lose these papers They",
      "Don’t ever lose these papers They are",
      "Don’t ever lose these papers They are of",
      "Don’t ever lose these papers They are of great",
      "Don’t ever lose these papers They are of great importance",
      "Don’t ever lose these papers They are of great importance to",
      "Don’t ever lose these papers They are of great importance to our",
      "Don’t ever miss",
      "Don’t ever miss a",
      "Don’t ever miss a good",
      "Don’t ever arrive",
      "Don’t ever arrive late",
      "Don’t ever arrive late for",
      "Don’t ever arrive late for an",
      "Do",
      "Do you",
      "Do you agree",
      "Do you agree that",
      "Do you agree that we",
      "Do you agree that we should",
      "Do you agree that we should start",
      "Do you agree with",
      "Do you agree with my",
      "Will",
      "Will he",
      "Will he agree",
      "Will he agree to",
      "Will he agree to the",
      "Will he agree to the conditions",
      "Will he agree to the conditions in",
      "Will he agree to the conditions in the",
      "Do you carry",
      "Do you carry this",
      "Do you carry this in",
      "Do you carry this in size",
      "Do you have",
      "Do you have this",
      "Do you have this in",
      "Do you have any",
      "Do you have any single",
      "Do you have any single rooms",
      "Do you have any tickets",
      "Do you have any shoes",
      "Do you have any shoes in",
      "Do you have any shoes in size",
      "Do you have any shoes in size 20",
      "Did",
      "Did you",
      "Did you use",
      "Did you use to",
      "Did you use to live",
      "Did you use to live in",
      "Did you use to get",
      "Did you use to get up",
      "You used",
      "You used to",
      "You used to smoke",
      "didn’t",
      "Do you feel",
      "Do you feel like",
      "Do you feel like going",
      "Do you feel like going for",
      "Do you feel like going for a",
      "Do you feel like going for a walk",
      "Do you feel like going for a walk on",
      "Do you feel like going for a walk on the",
      "Do you feel like going shopping",
      "Do you feel like going shopping at",
      "Do you feel like going shopping at the",
      "Do you feel like eating",
      "Do you feel like eating some",
      "Do you feel like eating some ice",
      "Do you feel like eating some ice cream",
      "Do you feel like eating some ice cream or",
      "Do you feel like eating some ice cream or having",
      "Do you feel like eating some ice cream or having cake",
      "Do you feel like eating some ice cream or having cake or",
      "Do you feel like having",
      "Do you feel like having some",
      "Do you feel like getting",
      "Do you feel like getting a",
      "Do you feel like getting a bite",
      "Do you feel like getting a bite to",
      "Would",
      "Would you",
      "Would you mind",
      "Would you mind if",
      "Would you mind if I",
      "Would you mind if I smoke",
      "Do you mind",
      "Do you mind opening",
      "Do you mind opening the",
      "Do you mind opening the window",
      "Do you mind opening the window It’s",
      "Do you mind opening the window It’s so",
      "Do you mind opening the window It’s so stuffy",
      "Do you mind opening the window It’s so stuffy in",
      "Do you mind if",
      "Do you mind if I",
      "Do you mind if I ask",
      "Do you mind if I ask you",
      "Do you mind if I ask you a",
      "Shouldn’t",
      "Shouldn’t we",
      "Shouldn’t we ask",
      "Shouldn’t we ask for",
      "Shouldn’t we ask for permission",
      "Shouldn’t we read",
      "Shouldn’t we read the",
      "Shouldn’t we read the directions",
      "Shouldn’t we read the directions before",
      "Shouldn’t we read the directions before we",
      "Shouldn’t we read the directions before we install",
      "Shouldn’t we read the directions before we install the",
      "Shouldn’t we read the directions before we install the air",
      "Shouldn’t we check",
      "Shouldn’t we check the",
      "Shouldn’t we check the weather",
      "Shouldn’t we check the weather before",
      "Shouldn’t we check the weather before we",
      "Shouldn’t we check the weather before we go",
      "Shouldn’t you",
      "Shouldn’t you try",
      "Shouldn’t you try to",
      "Shouldn’t you try to save",
      "Shouldn’t you try to save some",
      "Shouldn’t you try to save some money",
      "Shouldn’t you try to save some money rather",
      "Shouldn’t you try to save some money rather than",
      "Shouldn’t you try to save some money rather than spend",
      "Shouldn’t you try to save some money rather than spend it",
      "Have",
      "Have you",
      "Have you ever",
      "Have you ever been",
      "Have you ever been to",
      "Have you ever been to New",
      "Have you ever seen",
      "Have you ever wondered",
      "Have you ever wondered if",
      "Have you ever wondered if there",
      "Have you ever wondered if there is",
      "Have you ever wondered if there is life",
      "Have you ever wondered if there is life after",
      "Have you ever heard",
      "Have you ever heard of",
      "He",
      "He is",
      "He is either",
      "He is either drunk",
      "He is either drunk or",
      "It’s",
      "It’s either",
      "It’s either your",
      "It’s either your fault",
      "It’s either your fault or",
      "It’s either your fault or her",
      "Either",
      "Either you",
      "Either you are",
      "Either you are wrong",
      "Either you are wrong or",
      "Either you are wrong or I",
      "Don’t tell",
      "Don’t tell him",
      "Don’t tell him the",
      "Don’t tell him the bad",
      "Don’t tell him the bad news",
      "Don’t tell him the bad news until",
      "Don’t tell him the bad news until he",
      "Don’t tell him the bad news until he finishes",
      "Don’t tell him the bad news until he finishes his",
      "The secret",
      "The secret was",
      "The secret was not",
      "The secret was not discovered",
      "The secret was not discovered until",
      "The secret was not discovered until he",
      "The secret was not discovered until he was",
      "I won’t",
      "I won’t stop",
      "I won’t stop shouting",
      "I won’t stop shouting until",
      "I won’t stop shouting until you",
      "I won’t stop shouting until you let",
      "I won’t stop shouting until you let me",
      "He is as",
      "He is as poor",
      "He is as poor as",
      "He is as poor as a",
      "He is as poor as a church",
      "He is as fit",
      "He is as fit as",
      "He is as fit as a",
      "He is as fit as a fiddle",
      "He is as fit as a fiddle though",
      "He is as fit as a fiddle though he",
      "He is as fit as a fiddle though he is",
      "He is as fit as a fiddle though he is already",
      "Shelly’s",
      "Shelly’s father",
      "Shelly’s father is",
      "Shelly’s father is always",
      "Shelly’s father is always as",
      "Shelly’s father is always as busy",
      "Shelly’s father is always as busy as",
      "Shelly’s father is always as busy as a",
      "The twin",
      "The twin sisters",
      "The twin sisters are",
      "The twin sisters are as",
      "The twin sisters are as different",
      "The twin sisters are as different as",
      "The twin sisters are as different as night",
      "The twin sisters are as different as night and",
      "The lecture",
      "The lecture is",
      "The lecture is as",
      "The lecture is as dull",
      "The lecture is as dull as",
      "He is not",
      "He is not only",
      "but also",
      "He is not only a",
      "He is not only a good",
      "but also an",
      "but also an eloquent",
      "I’m",
      "I’m not",
      "I’m not only",
      "I’m not only going",
      "I’m not only going to",
      "I’m not only going to the",
      "I’m also",
      "I’m also going",
      "I’m also going to",
      "I’m also going to sing",
      "I’m also going to sing at",
      "Not",
      "Not only",
      "Not only do",
      "Not only do I",
      "Not only do I support",
      "so",
      "so do",
      "so do your",
      "Make",
      "Make yourself",
      "Make yourself at",
      "Make yourself at home",
      "Make yourself at home Help",
      "Make yourself at home Help yourself",
      "Make yourself at home Help yourself to",
      "Make yourself at home Help yourself to some",
      "Help",
      "Help yourself",
      "Help yourself to",
      "Help yourself to the",
      "Help yourself to some",
      "Help yourself to some steak",
      "Help yourself to some steak I",
      "Help yourself to some steak I made",
      "Help yourself to some steak I made it",
      "Help yourself to some steak I made it especially",
      "Help yourself to some steak I made it especially for",
      "I was",
      "I was so",
      "I was so interested",
      "I was so interested in",
      "I was so interested in the",
      "I was so interested in the film",
      "I was so interested in the film that",
      "I was so interested in the film that I",
      "I was so interested in the film that I went",
      "I was so interested in the film that I went to",
      "I was so interested in the film that I went to see",
      "I was so interested in the film that I went to see it",
      "I was so interested in the film that I went to see it several",
      "It’s so",
      "It’s so hot",
      "It’s so hot that",
      "It’s so hot that none",
      "It’s so hot that none of",
      "It’s so hot that none of us",
      "It’s so hot that none of us want",
      "It’s so hot that none of us want to",
      "It’s so hot that none of us want to go",
      "He speaks",
      "He speaks French",
      "He speaks French so",
      "He speaks French so well",
      "He speaks French so well that",
      "He speaks French so well that we",
      "He speaks French so well that we think",
      "He speaks French so well that we think he",
      "He speaks French so well that we think he is",
      "He speaks French so well that we think he is a",
      "How",
      "How about",
      "How about going",
      "How about going for",
      "How about going for a",
      "How about going for a spin",
      "How about going for a spin in",
      "How about going for a spin in my",
      "How about going for a spin in my new",
      "How about minding",
      "How about minding your",
      "How about minding your own",
      "How about those",
      "What",
      "What about",
      "What about your",
      "What about his",
      "What about his qualifications",
      "What about his qualifications for",
      "What about his qualifications for the",
      "You forgot",
      "You forgot to",
      "You forgot to bring",
      "You forgot to bring your",
      "You forgot to bring your homework",
      "You forgot to bring your homework again",
      "You forgot to bring your homework again How",
      "How come",
      "How come your",
      "How come your little",
      "How come your little sister",
      "How come your little sister is",
      "How come your little sister is so",
      "How come we",
      "How come we were",
      "How come we were not",
      "How come we were not invited",
      "How come we were not invited to",
      "How come we were not invited to the",
      "How dare",
      "How dare you",
      "How dare you call",
      "How dare you call me",
      "How dare you speak",
      "How dare you speak to",
      "How dare you speak to me",
      "How dare you speak to me like",
      "How dare he",
      "How dare he do",
      "How dare he do that",
      "How dare he do that to",
      "How dare you turn",
      "How dare you turn him",
      "How often",
      "How often is",
      "How often is there",
      "How often is there a",
      "How often is there a leap",
      "How often is there a flight",
      "How often is there a flight to",
      "How often do",
      "How often do you",
      "How often do you write",
      "How often do you write to",
      "How often do you write to your",
      "How do",
      "How do you",
      "How do you like",
      "How do you like your",
      "How do you like your new",
      "How does",
      "How does your",
      "How does your mother",
      "How does your mother like",
      "How does your mother like the",
      "How does your mother like the tea",
      "How long",
      "How long does",
      "How long does it",
      "How long does it take",
      "How long does it take to",
      "How long does it take to get",
      "How long does it take to get to",
      "How long does it take to get to the",
      "How long does it take to get to the station",
      "How long does it take to get to the station by",
      "How long will",
      "How long will it",
      "How long will it take",
      "How long will it take to",
      "How long will it take to build",
      "How long will it take to build the",
      "How long did",
      "How long did it",
      "How long did it take",
      "How long did it take you",
      "How long did it take you to",
      "How long did it take you to knit",
      "How long did it take you to knit this",
      "I can",
      "I can hardly",
      "I can hardly believe",
      "I can hardly believe that",
      "I can hardly believe that he",
      "I can hardly believe that he is",
      "I can hardly believe that he is deaf;",
      "I can hardly believe that he is deaf; he",
      "I can hardly believe that he is deaf; he can",
      "I can hardly believe that he is deaf; he can understand",
      "I can hardly believe that he is deaf; he can understand us",
      "I can hardly believe that he is deaf; he can understand us so",
      "I can hardly believe that Paul",
      "I can hardly believe that Paul was",
      "I can hardly believe that Paul was put",
      "I can hardly believe that Paul was put in",
      "I can hardly believe that Paul was put in prison",
      "I can hardly believe that Paul was put in prison for",
      "I can hardly believe what",
      "I can hardly believe what I",
      "I can hardly believe what I have",
      "I can’t",
      "I can’t help",
      "I can’t help laughing",
      "I can’t help laughing every",
      "I can’t help laughing every time",
      "I can’t help laughing every time I",
      "I can’t help laughing every time I think",
      "I can’t help laughing every time I think of",
      "I couldn’t",
      "I couldn’t help",
      "I couldn’t help noticing",
      "I couldn’t help noticing your",
      "I couldn’t help noticing your ring;",
      "I couldn’t help noticing your ring; it’s",
      "I can’t help but",
      "I can’t help but feel",
      "I can’t help but feel sorry",
      "I can’t help but feel sorry for",
      "I can’t help remembering",
      "I can’t help remembering how",
      "I can’t help remembering how beautiful",
      "I can’t help remembering how beautiful she",
      "I bet",
      "I bet we’re",
      "I bet he",
      "I bet he is",
      "I bet he is home",
      "I bet he will",
      "I bet he will win",
      "I bet he will win the",
      "I can’t say",
      "I can’t say for",
      "I can’t say who",
      "I can’t say who did",
      "I can’t say who did the",
      "I can’t say with",
      "I can’t say with any",
      "I can’t say with any certainty",
      "I can’t say with any certainty that",
      "I can’t say with any certainty that eating",
      "I can’t say with any certainty that eating less",
      "I can’t say with any certainty that eating less can",
      "I can’t say with any certainty that eating less can be",
      "I can’t say with any certainty that eating less can be a",
      "I can’t say with any certainty that eating less can be a cure",
      "I can’t say with any certainty that eating less can be a cure for",
      "I can’t wait",
      "I can’t wait to",
      "I can’t wait to see",
      "I can’t wait to see my",
      "I can’t wait to hear",
      "I can’t wait to hear from",
      "I can’t wait to buy",
      "I can’t wait to buy a",
      "I’d",
      "I’d hate",
      "I’d hate for",
      "I’d hate for you",
      "I’d hate for you to",
      "I’d hate for you to think",
      "I’d hate for you to think I",
      "I’d hate for you to think I didn’t",
      "I’d hate for you to miss",
      "I’d hate for you to miss the",
      "I’d hate for you to leave",
      "I’d hate for you to leave our",
      "I’d hate for you to get",
      "I’d like",
      "I’d like you",
      "I’d like you to",
      "I’d like you to fetch",
      "I’d like you to fetch some",
      "I’d like you to fetch some boiled",
      "I’d like you to send",
      "I’d like you to send for",
      "I’d like you to send for a",
      "I’d like you to look",
      "I’d like you to look after",
      "I’d like you to look after my",
      "I’d like you to look after my baby",
      "I’d like you to look after my baby for",
      "I’d like you to look after my baby for a",
      "If",
      "If  there",
      "If  there is",
      "If  there is one",
      "If  there is one thing",
      "If  there is one thing that",
      "If  there is one thing that  annoys",
      "it’s",
      "it’s people",
      "it’s people who",
      "it’s people who don’t",
      "it’s people who don’t keep",
      "If there",
      "If there is",
      "If there is one",
      "If there is one thing",
      "If there is one thing that",
      "If there is one thing that disappoints",
      "it’s his",
      "it’s his failure",
      "it’s his failure to",
      "it’s his failure to arrange",
      "it’s his failure to arrange his",
      "If there is one thing that upsets",
      "it’s my",
      "If there is one thing that surprises",
      "it’s his winning",
      "it’s his winning the",
      "If there is one thing that interests",
      "it’s fashion",
      "If it",
      "If it hadn’t",
      "If it hadn’t been",
      "If it hadn’t been for",
      "If it hadn’t been for your",
      "my",
      "my experiments",
      "my experiments would",
      "my experiments would have",
      "If it hadn’t been for the",
      "I would",
      "I would have",
      "If it hadn’t been for her",
      "If it hadn’t been for her careful",
      "the",
      "the party",
      "the party would",
      "the party would not",
      "the party would not have",
      "the party would not have been a",
      "Without",
      "Without my",
      "he would",
      "he would not",
      "he would not have",
      "Without your",
      "Without your financial",
      "we",
      "we could",
      "we could not",
      "we could not have",
      "we could not have finished",
      "we could not have finished the",
      "I dare",
      "I dare say",
      "I dare say you",
      "I dare say you will",
      "I dare say you will succeed",
      "I dare say you will succeed in",
      "I dare say you will succeed in the",
      "I dare say he",
      "I dare say he won’t",
      "I would imagine",
      "I would imagine he’s",
      "I’ve",
      "I’ve got",
      "I’ve got to",
      "I have",
      "I have got",
      "I have got to",
      "I have got to buy",
      "I have got to buy something",
      "I have got to buy something to",
      "I have got to mail",
      "I have got to mail some",
      "I have got to mail some cards",
      "I have got to mail some cards to",
      "I have got to mail some cards to my",
      "I’ve got to apologize",
      "I’ve got to apologize for",
      "I’ve got to apologize for troubling",
      "I’ve got to apologize for troubling you",
      "I’ve got to apologize for troubling you so",
      "You’ve",
      "You’ve got",
      "You’ve got to",
      "You’ve got to try",
      "You’ve got to try this",
      "You’ve got to try this dish;",
      "You’ve got to try this dish; it’s",
      "I’ll",
      "I’ll be",
      "I’ll be back",
      "I’ll be back as",
      "I’ll be back as soon",
      "I’ll be back as soon as",
      "I’ll work",
      "I’ll work as",
      "I’ll work as hard",
      "I’ll work as hard as",
      "I’ll work as hard as I",
      "Try",
      "Try to",
      "Try to be",
      "Try to be as",
      "Try to be as careful",
      "Try to be as careful as",
      "Come",
      "Come as",
      "Come as quickly",
      "Come as quickly as",
      "Run",
      "Run as",
      "Run as fast",
      "Run as fast as",
      "Run as fast as you",
      "I’d be",
      "I’d be grateful",
      "I’d be grateful for",
      "I’d be grateful for your",
      "I’d be grateful if",
      "I’d be grateful if you’d",
      "I’d be grateful if you’d be",
      "I’d be grateful if you’d give",
      "I’d be grateful if you’d give me",
      "I’d be grateful if you’d give me a",
      "I’d be grateful if you’d take",
      "I’d be grateful if you’d take care",
      "I’d be grateful if you’d take care of",
      "I’d be grateful if you’d take care of my",
      "I’d be grateful if you",
      "I’d be grateful if you danced",
      "I’d be grateful if you danced with",
      "I’ll let",
      "I’ll let you",
      "I’ll let you know",
      "I’ll let you know when",
      "I’ll let you know when I’m",
      "I’ll let you know when I’m leaving",
      "I’ll let you know when I’m leaving for",
      "I’ll let you know if",
      "I’ll let you know if I",
      "I’ll let you know if I can",
      "I’ll let you know if I can make",
      "I’ll let you know if I can make it",
      "I’ll let you know if I can make it for",
      "I’ll let you know if I get",
      "I’ll let you know when I",
      "I’ll let you know when I get",
      "I had",
      "I had no",
      "I had no idea",
      "I had no idea that",
      "I had no idea that she",
      "I had no idea that she was",
      "I had no idea that she was a",
      "He has",
      "He has no",
      "He has no idea",
      "He has no idea how",
      "He has no idea how to",
      "He has no idea how to operate",
      "He has no idea how to operate these",
      "I have no",
      "I have no idea",
      "I have no idea what",
      "I have no idea what time",
      "I have no idea what time it",
      "I’m looking",
      "I’m looking forward",
      "I’m looking forward to",
      "I’m looking forward to working",
      "I’m looking forward to working with",
      "I’m looking forward to coming",
      "I’m looking forward to coming to",
      "I’m looking forward to coming to China",
      "I’m really",
      "I’m really looking",
      "I’m really looking forward",
      "I’m really looking forward to",
      "I’m really looking forward to the",
      "I’m afraid",
      "I’m afraid you",
      "I’m afraid you didn’t",
      "I’m afraid you didn’t quite",
      "I’m afraid you didn’t quite get",
      "I’m afraid you didn’t quite get his",
      "A:",
      "A: Could",
      "A: Could I",
      "A: Could I speak",
      "A: Could I speak to",
      "B:",
      "B: I’m",
      "B: I’m afraid",
      "B: I’m afraid she",
      "B: I’m afraid she is",
      "B: I’m afraid she is not",
      "B: I’m afraid she is not in",
      "B: I’m afraid she is not in at",
      "B: I’m afraid she is not in at the",
      "I’m afraid we",
      "I’m afraid we are",
      "I’m afraid we are going",
      "I’m afraid we are going to",
      "I’m afraid we are going to be",
      "I’m afraid I",
      "I’m afraid I can’t",
      "I’m afraid I can’t make",
      "I’m calling",
      "I’m calling to",
      "I’m calling to say",
      "I’m calling to say goodbye",
      "I’m calling to say goodbye to",
      "I’m calling to tell",
      "I’m calling to tell you",
      "I’m calling to tell you that",
      "I’m calling to tell you that the",
      "I’m calling to tell you that the concert",
      "I’m calling to tell you that the concert begins",
      "I’m calling to tell you that the concert begins at",
      "I’m calling to book",
      "I’m calling to book two",
      "I’m calling to book two tickets",
      "I’m calling to book two tickets for",
      "I’m calling to book two tickets for tonight’s",
      "I’m calling to warn",
      "I’m calling to warn you",
      "I’m calling to warn you of",
      "I’m calling to warn you of the",
      "I’m calling to warn you of the coming",
      "I’m not really",
      "I’m not really happy",
      "I’m not really happy with",
      "I’m not really happy with their",
      "I’m not really happy with your",
      "I’m not really happy with your present",
      "I’m not really happy with my",
      "It",
      "It was",
      "It was Jack",
      "It was Jack who",
      "It was Jack who broke",
      "It was Jack who broke the",
      "It was Jack who broke the window",
      "It was Jack who broke the window when",
      "It was Jack who broke the window when we",
      "It was Jack who broke the window when we were",
      "It was Jack who broke the window when we were playing",
      "It is",
      "It is Jane",
      "It is Jane that",
      "It is Jane that I",
      "It is Jane that I want",
      "It is Jane that I want to",
      "It was here",
      "It was here in",
      "It was here in the",
      "It was here in the supermarket",
      "It was here in the supermarket that",
      "It was here in the supermarket that he",
      "It was here in the supermarket that he met",
      "It was here in the supermarket that he met his",
      "It was here in the supermarket that he met his first",
      "I really",
      "I really go",
      "I really go for",
      "I really go for this",
      "I really go for this house",
      "I really go for this house It’s",
      "She",
      "She goes",
      "She goes for",
      "She goes for tall",
      "She goes for tall and",
      "She goes for tall and handsome",
      "I don’t go",
      "I don’t go much",
      "I don’t go much for",
      "It’s too",
      "It’s too bad",
      "It’s too bad that",
      "It’s too bad that we",
      "It’s too bad that we lost",
      "It’s too bad that we lost the",
      "It’s too bad that we have",
      "It’s too bad that we have to",
      "It’s too bad that we have to cancel",
      "It’s too bad that we have to cancel the",
      "It’s too bad that you",
      "It’s too bad that you can’t",
      "It’s too bad that the",
      "It’s too bad that the rain",
      "It’s too bad that the rain spoiled",
      "It’s too bad that the rain spoiled our",
      "I’m thinking",
      "I’m thinking about",
      "I’m thinking about moving",
      "I’m thinking about moving to",
      "I’m thinking about moving to a",
      "I’m thinking about moving to a new",
      "I’m thinking about taking",
      "I’m thinking about taking a",
      "I’m thinking about taking a science",
      "I’m thinking about getting",
      "I’m thinking about getting a",
      "It’s my",
      "It’s my fault",
      "It’s my fault we",
      "It’s my fault we missed",
      "It’s my fault we missed the",
      "It’s my fault you",
      "It’s my fault you didn’t",
      "It’s my fault you didn’t get",
      "It’s my fault you didn’t get paid",
      "It’s my fault you didn’t get paid on",
      "It’s my fault we lost",
      "It’s my fault we lost the",
      "It’s on",
      "It’s on the",
      "It’s on the tip",
      "It’s on the tip of",
      "It’s on the tip of my",
      "let",
      "let me",
      "His",
      "His address",
      "His address is",
      "His address is on",
      "His address is on the",
      "His address is on the tip",
      "His address is on the tip of",
      "His address is on the tip of my",
      "wait",
      "wait a",
      "The question",
      "The question she",
      "The question she wanted",
      "The question she wanted to",
      "The question she wanted to ask",
      "The question she wanted to ask was",
      "The question she wanted to ask was on",
      "The question she wanted to ask was on the",
      "The question she wanted to ask was on the tip",
      "The question she wanted to ask was on the tip of",
      "The question she wanted to ask was on the tip of her",
      "A: Do",
      "A: Do you",
      "A: Do you want",
      "A: Do you want to",
      "A: Do you want to eat",
      "A: Do you want to eat a",
      "A: Do you want to eat a Western",
      "A: Do you want to eat a Western or",
      "A: Do you want to eat a Western or Chinese",
      "B: It’s",
      "B: It’s up",
      "B: It’s up to",
      "It’s up",
      "It’s up to",
      "It’s up to us",
      "It’s up to us to",
      "It’s up to us to help",
      "It’s up to us to help those",
      "It’s up to us to help those in",
      "It’s not",
      "It’s not up",
      "It’s not up to",
      "It’s not up to you",
      "It’s not up to you to",
      "It’s not up to you to tell",
      "It’s not up to you to tell me",
      "It’s not up to you to tell me how",
      "It’s not up to you to tell me how to",
      "It’s not up to you to tell me how to do",
      "It’s not up to you to tell me how to do my",
      "It is said",
      "It is said that",
      "It is said that he",
      "It is said that he is",
      "It is said that he is quite",
      "It is said that he is quite a",
      "It is said that he is quite a handsome",
      "It is said that he is quite a handsome young",
      "It’s said",
      "It’s said that",
      "It’s said that a",
      "It’s said that a new",
      "It’s said that a new president",
      "It’s said that a new president will",
      "It’s said that a new president will be",
      "It  should",
      "It  should be",
      "It  should be pointed",
      "It  should be pointed out",
      "It  should be pointed out  that",
      "It  should be pointed out  that  your",
      "It  should be pointed out  that  your proposals",
      "It  should be pointed out  that  your proposals are",
      "It  should be pointed out  that  your proposals are theoretically",
      "It  should be pointed out  that  your proposals are theoretically correct",
      "It  should be pointed out  that  your proposals are theoretically correct  but practically",
      "It has",
      "It has been",
      "It has been proven",
      "It has been proven that",
      "It has been proven that your",
      "It has been proven that your method",
      "It has been proven that your method is",
      "It has been proven that your method is the",
      "It will",
      "It will be",
      "It will be noted",
      "It will be noted that",
      "It will be noted that what",
      "It will be noted that what they",
      "It will be noted that what they have",
      "It will be noted that what they have done",
      "It will be noted that what they have done to",
      "It will be noted that what they have done to him",
      "It will be noted that what they have done to him is",
      "It’s your",
      "It’s your turn",
      "It’s your turn to",
      "It’s your turn to tell",
      "It’s your turn to tell a",
      "It’s your turn to sweep",
      "It’s your turn to sweep the",
      "It’s your turn to give",
      "It’s your turn to give a",
      "It may",
      "It may surprise",
      "but I",
      "but I paid",
      "but I paid off",
      "but I paid off all",
      "but I paid off all the",
      "but I paid off all the debts",
      "but I paid off all the debts in",
      "but I paid off all the debts in a",
      "but Maggie",
      "but Maggie refused",
      "but Maggie refused my",
      "but I bought",
      "but I bought all",
      "but I bought all these",
      "but I bought all these books",
      "but I bought all these books for",
      "but I bought all these books for 20",
      "but he’s",
      "but he’s just",
      "but he’s just been",
      "but he’s just been promoted",
      "but he’s just been promoted to",
      "but he",
      "but he was",
      "but he was once",
      "but he was once in",
      "It’s not that",
      "It’s not that I",
      "It’s not that I don’t",
      "It’s not that I don’t like",
      "It’s not that I don’t like the",
      "but I think",
      "but I think it",
      "but I think it is",
      "but I think it is too",
      "It’s not that I am",
      "It’s not that I am unwilling",
      "It’s not that I am unwilling to",
      "It’s not that I am unwilling to help",
      "but I’m",
      "but I’m tied",
      "but I’m tied up",
      "but I’m tied up with",
      "but I’m tied up with extra",
      "but I’m tied up with extra work",
      "It’s not  that",
      "It’s not  that  he",
      "It’s not  that  he doesn’t",
      "It’s not  that  he doesn’t need",
      "It’s not  that  he doesn’t need your",
      "but he thinks",
      "but he thinks it",
      "but he thinks it  will",
      "but he thinks it  will be",
      "but he thinks it  will be an inconvenience",
      "but he thinks it  will be an inconvenience to",
      "A",
      "A mountain",
      "A mountain is",
      "A mountain is not",
      "A mountain is not famous",
      "A mountain is not famous because",
      "A mountain is not famous because it",
      "A mountain is not famous because it is",
      "but because",
      "but because it",
      "but because it has",
      "but because it has some",
      "but because it has some spirit dwelling",
      "but because it has some spirit dwelling in",
      "I’ve had",
      "I’ve had enough",
      "I’ve had enough of",
      "I’ve had enough of her",
      "I’ve had enough of her continual",
      "I’ve had enough of your",
      "Haven’t",
      "Haven’t you",
      "Haven’t you had",
      "Haven’t you had enough",
      "Haven’t you had enough of",
      "Haven’t you had enough of him",
      "Haven’t you had enough of him I",
      "Haven’t you had enough of him I found",
      "Haven’t you had enough of him I found him",
      "Haven’t you had enough of him I found him so",
      "I’ve had enough of the",
      "I’ve had enough of the traffic",
      "I’ve had enough of this",
      "I wonder",
      "I wonder if",
      "I wonder if it",
      "I wonder if it would",
      "I wonder if it would be",
      "I wonder if it would be convenient",
      "I wonder if it would be convenient to",
      "I wonder if it would be convenient to visit",
      "I wonder if it would be convenient to visit you",
      "I wonder if it would be convenient to visit you next",
      "I wonder if Mr",
      "I wonder if Mr Wang",
      "I wonder if Mr Wang could",
      "I wonder if Mr Wang could arrange",
      "I wonder if Mr Wang could arrange a",
      "I wonder if Mr Wang could arrange a meeting",
      "I wonder if Mr Wang could arrange a meeting with",
      "I was wondering",
      "I was wondering if",
      "I was wondering if the",
      "I was wondering if the manager",
      "I was wondering if the manager would",
      "I was wondering if the manager would agree",
      "I was wondering if the manager would agree with",
      "I was wondering if the manager would agree with my",
      "I was wondering if you",
      "I was wondering if you could",
      "I was wondering if you could come",
      "I was wondering if you could come to",
      "I was wondering if you could come to the",
      "I was wondering if you could come to the meeting",
      "I was wondering if you could come to the meeting this",
      "I have been",
      "I have been learning",
      "I have been learning English",
      "I have been learning English for",
      "I have been learning English for almost",
      "I have been learning English for almost ten",
      "I have been living",
      "I have been living here",
      "I have been living here for",
      "I have been living here for thirty",
      "Where",
      "Where have",
      "Where have you",
      "Where have you been",
      "Where have you been We",
      "Where have you been We have",
      "Where have you been We have been",
      "Where have you been We have been looking",
      "Where have you been We have been looking for",
      "Where have you been We have been looking for you",
      "No",
      "No matter",
      "No matter what",
      "No matter what he",
      "don’t",
      "don’t believe",
      "No matter how",
      "No matter how you",
      "No matter how you do",
      "it",
      "it will",
      "it will be",
      "No matter where",
      "No matter where he",
      "he carries",
      "he carries his",
      "No matter how you spend",
      "No matter how you spend your",
      "tell",
      "tell me",
      "tell me about",
      "I would rather",
      "I would rather stay",
      "I would rather stay than",
      "He would",
      "He would rather",
      "He would rather work",
      "He would rather work all",
      "He would rather work all day",
      "He would rather work all day long",
      "He would rather work all day long than",
      "He would rather work all day long than do",
      "The mother",
      "The mother would",
      "The mother would rather",
      "The mother would rather die",
      "The mother would rather die than",
      "The mother would rather die than lose",
      "The mother would rather die than lose her",
      "She’d",
      "She’d rather",
      "She’d rather resign",
      "She’d rather resign than",
      "She’d rather resign than take",
      "She’d rather resign than take part",
      "She’d rather resign than take part in",
      "She’d rather resign than take part in such",
      "She’d rather resign than take part in such shameful",
      "She’d rather resign than take part in such shameful business",
      "Now",
      "Now that",
      "Now that I",
      "Now that I come",
      "Now that I come to",
      "Now that I come to think",
      "Now that I come to think about",
      "you’re",
      "you’re right",
      "you’re right to",
      "you’re right to dismiss",
      "how",
      "how ignorant",
      "how ignorant I",
      "Now that I think",
      "Now that I think about",
      "you",
      "you are",
      "you are wise",
      "you are wise not",
      "you are wise not to",
      "you are wise not to have",
      "you are wise not to have accepted",
      "he is a person",
      "he is a person really",
      "he is a person really worth",
      "You eat",
      "You eat so",
      "You eat so little",
      "You eat so little No",
      "You eat so little No wonder",
      "You eat so little No wonder you",
      "You eat so little No wonder you are",
      "You eat so little No wonder you are so",
      "Are you a",
      "Are you a librarian",
      "Are you a librarian No",
      "Are you a librarian No wonder",
      "Are you a librarian No wonder you",
      "Are you a librarian No wonder you are",
      "Are you a librarian No wonder you are so",
      "Are you a librarian No wonder you are so well",
      "There",
      "There is",
      "There is something",
      "There is something wrong",
      "There is something wrong with",
      "There is something wrong with your",
      "There is something wrong with your leg",
      "There is something wrong with your leg No",
      "There is something wrong with your leg No wonder",
      "There is something wrong with your leg No wonder you",
      "There is something wrong with your leg No wonder you walk",
      "There is something wrong with your leg No wonder you walk so",
      "I ran",
      "I ran to",
      "I ran to the",
      "I ran to the station",
      "I ran to the station only",
      "I ran to the station only to",
      "I ran to the station only to find",
      "I ran to the station only to find that",
      "I ran to the station only to find that the",
      "I ran to the station only to find that the train",
      "I ran to the station only to find that the train had",
      "She came",
      "She came home",
      "She came home excitedly",
      "She came home excitedly only",
      "She came home excitedly only to",
      "She came home excitedly only to find",
      "She came home excitedly only to find nobody",
      "She came home excitedly only to find nobody was",
      "I search",
      "I search desperately",
      "I search desperately for",
      "I search desperately for my",
      "only",
      "only to",
      "only to find",
      "only to find all",
      "only to find all my",
      "only to find all my money",
      "only to find all my money was",
      "I arrived",
      "I arrived at",
      "I arrived at the",
      "only to find I",
      "only to find I had",
      "only to find I had no",
      "only to find I had no money",
      "only to find I had no money on",
      "On",
      "On one",
      "but on",
      "but on the",
      "but on the other",
      "he is very",
      "he is very obedient",
      "he is very obedient to",
      "he is very obedient to his",
      "he is very obedient to his wife;",
      "he is very obedient to his wife; on",
      "he is very obedient to his wife; on the",
      "he is very obedient to his wife; on the other",
      "he treats",
      "he treats his parents",
      "Jason",
      "Jason does",
      "Jason does everything",
      "Jason does everything in",
      "Jason does everything in the",
      "Jason does everything in the  office;",
      "Jason does everything in the  office;  on",
      "Jason does everything in the  office;  on the",
      "Jason does everything in the  office;  on the other",
      "he does",
      "he does nothing",
      "he does nothing at",
      "As a",
      "he is very patient",
      "he is very patient in",
      "he is very patient in class;",
      "he is very patient in class; but",
      "he is very patient in class; but on",
      "he is very patient in class; but on the",
      "he is very patient in class; but on the other",
      "he is not",
      "he is not so patient",
      "he is not so patient with",
      "he is not so patient with his",
      "he is not so patient with his own",
      "Once",
      "Once you",
      "you can’t",
      "you can’t change",
      "you can’t change your",
      "Once you have",
      "Once you have a",
      "take",
      "take the",
      "take the medicine",
      "take the medicine twice",
      "take the medicine twice a",
      "Once he",
      "Once he finds",
      "Once he finds out",
      "Once he finds out what",
      "Once he finds out what you’ve",
      "he’ll",
      "he’ll get",
      "Speaking",
      "Speaking of",
      "Speaking of the",
      "have",
      "have you",
      "have you seen",
      "have you seen “The",
      "I know",
      "I know a",
      "I know a lot",
      "I know a lot of",
      "I know a lot of people",
      "I know a lot of people who",
      "I know a lot of people who don’t",
      "I know a lot of people who don’t pay",
      "I know a lot of people who don’t pay bus",
      "have you seen him",
      "China",
      "China is",
      "China is called",
      "China is called “the",
      "China is called “the kingdom",
      "China is called “the kingdom of",
      "See",
      "See that",
      "See that the",
      "See that the door",
      "See that the door is",
      "See that the door is locked",
      "See that the door is locked before",
      "See that the door is locked before you",
      "See that you",
      "See that you have",
      "See that you have enough",
      "See that you have enough sleep",
      "See that you have enough sleep every",
      "See that you go",
      "See that you go to",
      "See that you go to see",
      "See that you go to see your",
      "See that you go to see your parents",
      "Thanks",
      "Thanks to",
      "Thanks to their",
      "we accomplished",
      "we accomplished the",
      "we accomplished the task",
      "we accomplished the task on",
      "lots",
      "lots of",
      "lots of tasks",
      "lots of tasks are",
      "lots of tasks are now",
      "Thanks to your",
      "Thanks to your timely",
      "I didn’t",
      "I didn’t make",
      "I didn’t make a",
      "we lost",
      "we lost our",
      "The more",
      "The more you",
      "The more you put",
      "The more you put your",
      "The more you put your heart",
      "The more you put your heart into",
      "the more",
      "the more you’ll",
      "the more you’ll be",
      "the more you’ll be interested",
      "the more you’ll be interested in",
      "the more you",
      "the more you will",
      "The earlier",
      "The earlier you",
      "The earlier you set",
      "The earlier you set about",
      "The earlier you set about your",
      "the sooner",
      "the sooner you",
      "the sooner you will",
      "the sooner you will finish",
      "The first",
      "The first thing",
      "The first thing I’m",
      "The first thing I’m going",
      "The first thing I’m going to",
      "The first thing I’m going to do",
      "The first thing I’m going to do when",
      "The first thing I’m going to do when I",
      "The first thing I’m going to do when I get",
      "The first thing I’m going to do when I get home",
      "The first thing I’m going to do when I get home is",
      "The first thing I’m going to do when I get home is sleep",
      "The first thing I’m going to do when I get home is sleep for",
      "The first thing I’m going to do when I get home is sleep for a",
      "The first thing I’m going to do when I get home is sleep for a whole",
      "The first thing I’m going to do when I get a",
      "The first thing I’m going to do when I get a pay",
      "The first thing I’m going to do when I get a pay raise",
      "The first thing I’m going to do when I get a pay raise is",
      "The first thing I’m going to do when I get a pay raise is to",
      "The first thing I’m going to do when I get a pay raise is to treat",
      "The first thing I’m going to do when I get a pay raise is to treat you",
      "The first thing I’m going to do when I get a pay raise is to treat you to",
      "The first thing I’m going to do when I spend",
      "The first thing I’m going to do when I spend my",
      "The first thing I’m going to do when I spend my vacation",
      "The first thing I’m going to do when I spend my vacation in",
      "The first thing I’m going to do when I spend my vacation in the",
      "The first thing I’m going to do when I spend my vacation in the country",
      "The first thing I’m going to do when I spend my vacation in the country is",
      "There is nothing",
      "There is nothing as",
      "There is nothing as exciting",
      "There is nothing as exciting as",
      "There is nothing as exciting as meeting",
      "There is nothing as exciting as meeting an",
      "There is nothing as exciting as meeting an old",
      "There is nothing as exciting as meeting an old friend",
      "For",
      "there is",
      "there is nothing",
      "there is nothing as",
      "there is nothing as enjoyable",
      "there is nothing as enjoyable as",
      "there is nothing as enjoyable as reading",
      "there is nothing as enjoyable as reading a",
      "there is nothing as enjoyable as reading a novel",
      "there is nothing as enjoyable as reading a novel on",
      "there is nothing as enjoyable as reading a novel on the",
      "There is nothing as pleasant",
      "There is nothing as pleasant as",
      "There is nothing as pleasant as spending",
      "There is nothing as pleasant as spending a",
      "There is nothing as pleasant as spending a weekend",
      "There is nothing as pleasant as spending a weekend in",
      "There is nothing as pleasant as spending a weekend in the",
      "There is nothing as refreshing",
      "There is nothing as refreshing as",
      "There is nothing as refreshing as having",
      "There is nothing as refreshing as having a",
      "There is nothing as refreshing as having a good",
      "There is nothing I",
      "There is nothing I like",
      "There is nothing I like better",
      "There is nothing I like better than",
      "There is nothing I like better than listening",
      "There is nothing I like better than listening to",
      "There is nothing I like better than listening to the",
      "There is nothing women",
      "There is nothing women like",
      "There is nothing women like better",
      "There is nothing women like better than",
      "There is nothing she",
      "There is nothing she likes",
      "There is nothing she likes better",
      "There is nothing she likes better than",
      "There is nothing she likes better than chatting",
      "There is nothing she likes better than chatting with",
      "We’d",
      "We’d be",
      "We’d be better",
      "We’d be better off",
      "We’d be better off without",
      "We’d be better off without them",
      "We’d be better off without them as",
      "We’d be better off without him",
      "We’d be better off without him at",
      "We’d be better off without him at the",
      "They’d",
      "They’d be",
      "They’d be better",
      "They’d be better off",
      "They’d be better off without",
      "They’d be better off without their",
      "They’d be better off without their wives",
      "They’d be better off without their wives around",
      "I’d be better",
      "I’d be better off",
      "I’d be better off without",
      "I’d be better off without the",
      "I’d be better off without the incident",
      "I’d be better off without the incident on",
      "I’d be better off without the incident on my",
      "Thank",
      "Thank you",
      "Thank you for",
      "Thank you for what",
      "Thank you for what you",
      "Thank you for what you have",
      "Thank you for what you have done",
      "Thank you for what you have done for",
      "Thank you for your",
      "Thank you for the",
      "Thank you for giving",
      "Thank you for giving me",
      "Thank you for giving me a",
      "We’d better",
      "We’d better buy",
      "We’d better buy a",
      "You’d",
      "You’d better",
      "You’d better not",
      "You’d better not ask",
      "You had",
      "You had best",
      "You had best accept",
      "You had best accept his",
      "You had best set",
      "You had best set out",
      "What became",
      "What became of",
      "What became of the",
      "What became of the poor",
      "What will",
      "What will become",
      "What will become of",
      "What will become of my",
      "What will become of my family",
      "What will become of my family if",
      "What will become of my family if my",
      "What will become of my family if my father",
      "What will become of my family if my father goes",
      "What will become of my dog",
      "What will become of my dog during",
      "What will become of my dog during my",
      "What will become of the",
      "What will become of the water",
      "What will become of the water if",
      "What will become of the water if we",
      "What will become of the water if we put",
      "What will become of the water if we put it",
      "What will become of the water if we put it outside",
      "What will become of the water if we put it outside during",
      "What will become of the water if we put it outside during the",
      "We may",
      "We may as",
      "We may as well",
      "We may as well buy",
      "We may as well buy a",
      "We may as well buy a Benz",
      "We may as well buy a Benz since",
      "We may as well buy a Benz since you",
      "We may as well buy a Benz since you don’t",
      "We may as well buy a Benz since you don’t like",
      "We may as well have",
      "We may as well have a",
      "We may as well have a try",
      "We may as well have a try since",
      "We may as well have a try since it’s",
      "We may as well have a try since it’s worth",
      "We may as well take",
      "We may as well take the",
      "We may as well take the risk",
      "We may as well take the risk Nothing",
      "What can",
      "What can I",
      "What can I do",
      "What can I do for",
      "What can I do to",
      "What can I do to cheer",
      "What can I do to cheer her",
      "What can I do to make",
      "What can I do to make him",
      "What can I do to stop",
      "I’ve got the",
      "I’ve got the what-do-you-call-it",
      "I’ve got the what-do-you-call-it for",
      "I cannot",
      "I cannot find",
      "I cannot find the",
      "She’s",
      "She’s just",
      "She’s just gone",
      "She’s just gone out",
      "She’s just gone out with",
      "She’s just gone out with old",
      "What’s-his-name",
      "What’s-his-name called",
      "What’s-his-name called you",
      "What’s-his-name called you this",
      "Where did",
      "Where did you",
      "Where did you put",
      "Where did you put the",
      "What do",
      "What do you",
      "What do you say",
      "What do you say about",
      "What do you say about going",
      "What do you say about going to",
      "What do you say about going to the",
      "What do you say about going to the cinema",
      "What do you say about going to the cinema this",
      "Let’s",
      "Let’s go",
      "Let’s go by",
      "Let’s go by plane",
      "Let’s go by plane What",
      "Let’s go by plane What do",
      "Let’s go by plane What do you",
      "What do you say about some",
      "What do you say about some light",
      "What do you mean",
      "What do you mean by",
      "What do you mean by saying",
      "What do you mean by canceling",
      "What do you mean by canceling your",
      "What do you mean by “out",
      "What do you mean by “out of",
      "What do you mean by “out of the",
      "What do you mean by asking",
      "What do you mean by asking such",
      "What do you mean by asking such a",
      "What if",
      "What if it",
      "What if it rains",
      "What if it rains when",
      "What if it rains when we",
      "What if it rains when we have",
      "What if it rains when we have no",
      "What if it rains when we have no umbrella",
      "What if it rains when we have no umbrella with",
      "What if they",
      "What if they are",
      "What if they are against",
      "What if we",
      "What if we get",
      "What if we get lost",
      "What if we get lost in",
      "What if we get lost in the",
      "What if they don’t",
      "What if they don’t approve",
      "What if they don’t approve of",
      "What if they don’t approve of our",
      "What if they don’t approve of our earning",
      "What if they don’t approve of our earning some",
      "What if they don’t approve of our earning some money",
      "What if they don’t approve of our earning some money in",
      "What if they don’t approve of our earning some money in our",
      "What if they don’t approve of our earning some money in our spare",
      "What is",
      "What is it",
      "What did",
      "What did you",
      "What did you say",
      "What did you say that",
      "What do you need",
      "What do you need so",
      "What do you need so much",
      "What do you need so much money",
      "What I’m",
      "What I’m trying",
      "What I’m trying to",
      "What I’m trying to say",
      "What I’m trying to say is",
      "What I’m trying to say is that",
      "What I’m trying to say is that he",
      "What I’m trying to say is that he is",
      "What I’m trying to say is that he is a",
      "What I’m trying to say is that he is a good",
      "What I’m trying to say is that it’s",
      "What I’m trying to say is that it’s worth",
      "What I’m trying to say is that human",
      "What I’m trying to say is that human nature",
      "What I’m trying to say is that human nature doesn’t",
      "What I’m trying to say is that you",
      "What I’m trying to say is that you should",
      "What I’m trying to say is that you should think",
      "What I’m trying to say is that you should think of",
      "What I’m trying to say is that smoking",
      "What I’m trying to say is that smoking is",
      "What would",
      "What would you",
      "What would you do",
      "What would you do if",
      "What would you do if you",
      "What would you do if you were",
      "What would you do if you were in",
      "What would you do if you were in my",
      "What would you do if you had",
      "What would you do if you had a",
      "What would you do if you had a lot",
      "What would you do if you had a lot of",
      "What would you do if the",
      "What would you do if the rumors",
      "What would you do if the rumors were",
      "What’s",
      "What’s the",
      "What’s the matter",
      "What’s the matter with",
      "What’s the matter with your",
      "What’s the matter with your finger",
      "What’s the matter with your finger It’s",
      "What’s wrong",
      "What’s wrong with",
      "What’s wrong with this",
      "Mum",
      "Mum You",
      "Mum You look",
      "Mum You look so",
      "What’s wrong with your",
      "Where can",
      "Where can I",
      "Where can I get",
      "Where can I get a",
      "Where can I find",
      "Where can I find a",
      "What’s the use",
      "What’s the use of",
      "What’s the use of talking",
      "What’s the use of talking about",
      "What’s the use of crying",
      "What’s the use of crying over",
      "What’s the use of crying over spilt",
      "What’s the point",
      "What’s the point of",
      "What’s the point of arguing",
      "What’s the point of arguing with",
      "What’s the point of worrying",
      "What’s the point of worrying about",
      "Where there",
      "Where there are",
      "there are",
      "there are ways",
      "there are ways to",
      "there are ways to get",
      "there are ways to get over",
      "Where there is",
      "there are jealousy",
      "there are jealousy and",
      "Where there is a",
      "there is a",
      "What’s your",
      "What’s your favorite",
      "Who",
      "Who is",
      "Who is your",
      "Who is your favorite",
      "Who is your favorite film",
      "Which",
      "Which is",
      "Which is your",
      "Which is your favorite",
      "Why",
      "Why not",
      "Why not try",
      "Why not try to",
      "Why not try to persuade",
      "Why not try to persuade him",
      "Why not try to persuade him to",
      "Why not try to persuade him to give",
      "Why not try to persuade him to give up",
      "Why don’t",
      "Why don’t you",
      "Why don’t you go",
      "Why don’t you go ask",
      "Why don’t you go ask the",
      "Why not buy",
      "Why not buy some",
      "Why not buy some ready-made",
      "A: Let’s",
      "A: Let’s go",
      "A: Let’s go to",
      "A: Let’s go to see",
      "A: Let’s go to see a",
      "A: Let’s go to see a film",
      "why",
      "Would you care",
      "Would you care for",
      "Would you care for something",
      "Would you care for something to",
      "Would you care for some",
      "Would you like",
      "Would you like to",
      "Would you like to borrow",
      "Would you like to borrow my",
      "Would you like to try",
      "You only",
      "You only have",
      "You only have to",
      "You only have to ask",
      "You only have to ask her",
      "You only have to ask her in",
      "You only have to ask her in order",
      "You only have to ask her in order to",
      "You only have to ask her in order to know",
      "You only have to ask her in order to know what",
      "You only have to ask her in order to know what has",
      "You only have to call",
      "You only have to call her",
      "You only have to call her in",
      "You only have to call her in order",
      "You only have to call her in order to",
      "You only have to call her in order to know",
      "You only have to call her in order to know whether",
      "You only have to call her in order to know whether she",
      "You only have to call her in order to know whether she will",
      "You only have to call her in order to know whether she will come",
      "You only have to call her in order to know whether she will come or",
      "I only",
      "I only have",
      "I only have to",
      "I only have to consult",
      "I only have to consult the",
      "I only have to consult the digital",
      "I only have to consult the digital dictionary",
      "I only have to consult the digital dictionary in",
      "I only have to consult the digital dictionary in order",
      "I only have to consult the digital dictionary in order to",
      "I only have to consult the digital dictionary in order to find",
      "I only have to consult the digital dictionary in order to find out",
      "I only have to consult the digital dictionary in order to find out the",
      "I only have to consult the digital dictionary in order to find out the meaning",
      "I only have to consult the digital dictionary in order to find out the meaning of a",
      "I only have to consult the digital dictionary in order to find out the meaning of a word",
      "I only have to consult the digital dictionary in order to find out the meaning of a word I",
      "I only have to consult the digital dictionary in order to find out the meaning of a word I don’t",
      "You only have to ask the",
      "You only have to ask the teacher",
      "You only have to ask the teacher in",
      "You only have to ask the teacher in order",
      "You only have to ask the teacher in order to",
      "You only have to ask the teacher in order to solve",
      "You only have to ask the teacher in order to solve the",
      "You only have to get",
      "You only have to get some",
      "You only have to get some newspapers",
      "You only have to get some newspapers in",
      "You only have to get some newspapers in order",
      "You only have to get some newspapers in order to",
      "You only have to get some newspapers in order to find",
      "You only have to get some newspapers in order to find the",
      "You only have to get some newspapers in order to find the advertisements you",
      "You are not",
      "You are not to",
      "You are not to doze",
      "You are not to doze off",
      "You are not to doze off in",
      "You are not to waste",
      "You are not to waste your",
      "You are not to waste your time",
      "You are not to waste your time doing",
      "You are not to scribble",
      "You are not to scribble on",
      "You are not to scribble on the",
      "You are not to take",
      "You are not to take photos",
      "You are not to take photos in",
      "You are not to take photos in the",
      "You can",
      "You can never",
      "You can never be",
      "You can never be too",
      "You can never be too careful",
      "We cannot",
      "We cannot praise",
      "We cannot praise him",
      "We cannot praise him enough",
      "We cannot praise him enough as",
      "We cannot praise him enough as a",
      "One",
      "One cannot",
      "One cannot practice",
      "One cannot practice enough",
      "One cannot practice enough when",
      "One cannot practice enough when learning",
      "One cannot practice enough when learning a",
      "One cannot practice enough when learning a foreign",
      "You can never overestimate",
      "You can never overestimate Shakespeare’s",
      "You can never over-emphasize",
      "You can never over-emphasize the",
      "You can never over-emphasize the importance",
      "You can never over-emphasize the importance of",
      "You can never over-emphasize the importance of physical",
      "Whether",
      "Whether it",
      "Whether it rains",
      "Whether it rains or",
      "we’ll",
      "we’ll hold",
      "we’ll hold the",
      "we’ll hold the sports",
      "They’ll",
      "They’ll find",
      "They’ll find out",
      "They’ll find out the",
      "whether",
      "whether or",
      "whether or not",
      "whether or not you",
      "whether or not you tell",
      "whether or not you tell it",
      "whether or not you tell it to",
      "Whether or",
      "Whether or not",
      "Whether or not we",
      "Whether or not we like",
      "we have",
      "we have to",
      "we have to accept",
      "Whether you",
      "Whether you are",
      "Whether you are willing",
      "Whether you are willing or",
      "you have",
      "you have to",
      "you have to do",
    ];

    const v = phrases.map(
      (x) => `{
        english: "${x.toLowerCase()}",
        french: "",
        spanish: "",
    }`
    );

    fs.writeFile("phraseLink.js", `export default  [${v}]`, (err) => console.log(err));

    res.status(200).json("sds");
    return;

    return res.status(200).json("success");
  } catch (error) {
    // log errors only in development
    process.env.NODE_ENV !== "production" && console.log(error);
    return res.status(401).json(false);
  }
};
